server:
  port: 8081

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5432/fintrack_auth
    username: fintrack
    password: fintrack123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    default-property-inclusion: non_null

jwt:
  secret: "fintrack-super-secret-key-must-be-at-least-256-bits-long-for-hs256-algorithm"
  expiration: 900000
  refresh-expiration: 604800000

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  swagger-ui:
    path: /swagger-ui.html